name: 'Codeowners automerge'
description: 'Automerges PRs from code owners that change only owned code'
author: 'Loris Cro'

branding:
  icon: git-merge
  color: orange

inputs:
  cwd:
    description: 'The path to the root folder where it should look for code owners'
    default: '.github/'
    required: false

  merge_method:
    description: "The merge strategy to use: 'merge', 'squash' or 'rebase'"
    default: 'merge'
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'
